# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@ampproject/remapping-2.2.0" = {
      name = "_at_ampproject_slash_remapping";
      packageName = "@ampproject/remapping";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.2.0.tgz";
        sha512 = "qRmjj8nj9qmLTQXXmaR1cck3UXSRMPrbsLJAasZpF+t3riI71BXed5ebIOYwQntykeZuhjsdweEc9BxH5Jc26w==";
      };
    };
    "@babel/code-frame-7.18.6" = {
      name = "_at_babel_slash_code-frame";
      packageName = "@babel/code-frame";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.18.6.tgz";
        sha512 = "TDCmlK5eOvH+eH7cdAFlNXeVJqWIQ7gW9tY1GJIpUtFb6CmjVyq2VM3u71bOyR8CRihcCgMUYoDNyLXao3+70Q==";
      };
    };
    "@babel/compat-data-7.19.1" = {
      name = "_at_babel_slash_compat-data";
      packageName = "@babel/compat-data";
      version = "7.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/compat-data/-/compat-data-7.19.1.tgz";
        sha512 = "72a9ghR0gnESIa7jBN53U32FOVCEoztyIlKaNoU05zRhEecduGK9L9c3ww7Mp06JiR+0ls0GBPFJQwwtjn9ksg==";
      };
    };
    "@babel/core-7.19.1" = {
      name = "_at_babel_slash_core";
      packageName = "@babel/core";
      version = "7.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/core/-/core-7.19.1.tgz";
        sha512 = "1H8VgqXme4UXCRv7/Wa1bq7RVymKOzC7znjyFM8KiEzwFqcKUKYNoQef4GhdklgNvoBXyW4gYhuBNCM5o1zImw==";
      };
    };
    "@babel/generator-7.19.0" = {
      name = "_at_babel_slash_generator";
      packageName = "@babel/generator";
      version = "7.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/generator/-/generator-7.19.0.tgz";
        sha512 = "S1ahxf1gZ2dpoiFgA+ohK9DIpz50bJ0CWs7Zlzb54Z4sG8qmdIrGrVqmy1sAtTVRb+9CU6U8VqT9L0Zj7hxHVg==";
      };
    };
    "@babel/helper-compilation-targets-7.19.1" = {
      name = "_at_babel_slash_helper-compilation-targets";
      packageName = "@babel/helper-compilation-targets";
      version = "7.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-compilation-targets/-/helper-compilation-targets-7.19.1.tgz";
        sha512 = "LlLkkqhCMyz2lkQPvJNdIYU7O5YjWRgC2R4omjCTpZd8u8KMQzZvX4qce+/BluN1rcQiV7BoGUpmQ0LeHerbhg==";
      };
    };
    "@babel/helper-environment-visitor-7.18.9" = {
      name = "_at_babel_slash_helper-environment-visitor";
      packageName = "@babel/helper-environment-visitor";
      version = "7.18.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-environment-visitor/-/helper-environment-visitor-7.18.9.tgz";
        sha512 = "3r/aACDJ3fhQ/EVgFy0hpj8oHyHpQc+LPtJoY9SzTThAsStm4Ptegq92vqKoE3vD706ZVFWITnMnxucw+S9Ipg==";
      };
    };
    "@babel/helper-function-name-7.19.0" = {
      name = "_at_babel_slash_helper-function-name";
      packageName = "@babel/helper-function-name";
      version = "7.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-function-name/-/helper-function-name-7.19.0.tgz";
        sha512 = "WAwHBINyrpqywkUH0nTnNgI5ina5TFn85HKS0pbPDfxFfhyR/aNQEn4hGi1P1JyT//I0t4OgXUlofzWILRvS5w==";
      };
    };
    "@babel/helper-hoist-variables-7.18.6" = {
      name = "_at_babel_slash_helper-hoist-variables";
      packageName = "@babel/helper-hoist-variables";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-hoist-variables/-/helper-hoist-variables-7.18.6.tgz";
        sha512 = "UlJQPkFqFULIcyW5sbzgbkxn2FKRgwWiRexcuaR8RNJRy8+LLveqPjwZV/bwrLZCN0eUHD/x8D0heK1ozuoo6Q==";
      };
    };
    "@babel/helper-module-imports-7.18.6" = {
      name = "_at_babel_slash_helper-module-imports";
      packageName = "@babel/helper-module-imports";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-imports/-/helper-module-imports-7.18.6.tgz";
        sha512 = "0NFvs3VkuSYbFi1x2Vd6tKrywq+z/cLeYC/RJNFrIX/30Bf5aiGYbtvGXolEktzJH8o5E5KJ3tT+nkxuuZFVlA==";
      };
    };
    "@babel/helper-module-transforms-7.19.0" = {
      name = "_at_babel_slash_helper-module-transforms";
      packageName = "@babel/helper-module-transforms";
      version = "7.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-module-transforms/-/helper-module-transforms-7.19.0.tgz";
        sha512 = "3HBZ377Fe14RbLIA+ac3sY4PTgpxHVkFrESaWhoI5PuyXPBBX8+C34qblV9G89ZtycGJCmCI/Ut+VUDK4bltNQ==";
      };
    };
    "@babel/helper-simple-access-7.18.6" = {
      name = "_at_babel_slash_helper-simple-access";
      packageName = "@babel/helper-simple-access";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-simple-access/-/helper-simple-access-7.18.6.tgz";
        sha512 = "iNpIgTgyAvDQpDj76POqg+YEt8fPxx3yaNBg3S30dxNKm2SWfYhD0TGrK/Eu9wHpUW63VQU894TsTg+GLbUa1g==";
      };
    };
    "@babel/helper-split-export-declaration-7.18.6" = {
      name = "_at_babel_slash_helper-split-export-declaration";
      packageName = "@babel/helper-split-export-declaration";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-split-export-declaration/-/helper-split-export-declaration-7.18.6.tgz";
        sha512 = "bde1etTx6ZyTmobl9LLMMQsaizFVZrquTEHOqKeQESMKo4PlObf+8+JA25ZsIpZhT/WEd39+vOdLXAFG/nELpA==";
      };
    };
    "@babel/helper-string-parser-7.18.10" = {
      name = "_at_babel_slash_helper-string-parser";
      packageName = "@babel/helper-string-parser";
      version = "7.18.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-string-parser/-/helper-string-parser-7.18.10.tgz";
        sha512 = "XtIfWmeNY3i4t7t4D2t02q50HvqHybPqW2ki1kosnvWCwuCMeo81Jf0gwr85jy/neUdg5XDdeFE/80DXiO+njw==";
      };
    };
    "@babel/helper-validator-identifier-7.19.1" = {
      name = "_at_babel_slash_helper-validator-identifier";
      packageName = "@babel/helper-validator-identifier";
      version = "7.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-identifier/-/helper-validator-identifier-7.19.1.tgz";
        sha512 = "awrNfaMtnHUr653GgGEs++LlAvW6w+DcPrOliSMXWCKo597CwL5Acf/wWdNkf/tfEQE3mjkeD1YOVZOUV/od1w==";
      };
    };
    "@babel/helper-validator-option-7.18.6" = {
      name = "_at_babel_slash_helper-validator-option";
      packageName = "@babel/helper-validator-option";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helper-validator-option/-/helper-validator-option-7.18.6.tgz";
        sha512 = "XO7gESt5ouv/LRJdrVjkShckw6STTaB7l9BrpBaAHDeF5YZT+01PCwmR0SJHnkW6i8OwW/EVWRShfi4j2x+KQw==";
      };
    };
    "@babel/helpers-7.19.0" = {
      name = "_at_babel_slash_helpers";
      packageName = "@babel/helpers";
      version = "7.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/helpers/-/helpers-7.19.0.tgz";
        sha512 = "DRBCKGwIEdqY3+rPJgG/dKfQy9+08rHIAJx8q2p+HSWP87s2HCrQmaAMMyMll2kIXKCW0cO1RdQskx15Xakftg==";
      };
    };
    "@babel/highlight-7.18.6" = {
      name = "_at_babel_slash_highlight";
      packageName = "@babel/highlight";
      version = "7.18.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/highlight/-/highlight-7.18.6.tgz";
        sha512 = "u7stbOuYjaPezCuLj29hNW1v64M2Md2qupEKP1fHc7WdOA3DgLh37suiSrZYY7haUB7iBeQZ9P1uiRF359do3g==";
      };
    };
    "@babel/parser-7.19.1" = {
      name = "_at_babel_slash_parser";
      packageName = "@babel/parser";
      version = "7.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/parser/-/parser-7.19.1.tgz";
        sha512 = "h7RCSorm1DdTVGJf3P2Mhj3kdnkmF/EiysUkzS2TdgAYqyjFdMQJbVuXOBej2SBJaXan/lIVtT6KkGbyyq753A==";
      };
    };
    "@babel/runtime-7.19.0" = {
      name = "_at_babel_slash_runtime";
      packageName = "@babel/runtime";
      version = "7.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/runtime/-/runtime-7.19.0.tgz";
        sha512 = "eR8Lo9hnDS7tqkO7NsV+mKvCmv5boaXFSZ70DnfhcgiEne8hv9oCEd36Klw74EtizEqLsy4YnW8UWwpBVolHZA==";
      };
    };
    "@babel/template-7.18.10" = {
      name = "_at_babel_slash_template";
      packageName = "@babel/template";
      version = "7.18.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/template/-/template-7.18.10.tgz";
        sha512 = "TI+rCtooWHr3QJ27kJxfjutghu44DLnasDMwpDqCXVTal9RLp3RSYNh4NdBrRP2cQAoG9A8juOQl6P6oZG4JxA==";
      };
    };
    "@babel/traverse-7.19.1" = {
      name = "_at_babel_slash_traverse";
      packageName = "@babel/traverse";
      version = "7.19.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/traverse/-/traverse-7.19.1.tgz";
        sha512 = "0j/ZfZMxKukDaag2PtOPDbwuELqIar6lLskVPPJDjXMXjfLb1Obo/1yjxIGqqAJrmfaTIY3z2wFLAQ7qSkLsuA==";
      };
    };
    "@babel/types-7.19.0" = {
      name = "_at_babel_slash_types";
      packageName = "@babel/types";
      version = "7.19.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@babel/types/-/types-7.19.0.tgz";
        sha512 = "YuGopBq3ke25BVSiS6fgF49Ul9gH1x70Bcr6bqRLjWCkcX8Hre1/5+z+IiWOIerRMSSEfGZVB9z9kyq7wVs9YA==";
      };
    };
    "@emotion/cache-11.10.3" = {
      name = "_at_emotion_slash_cache";
      packageName = "@emotion/cache";
      version = "11.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/cache/-/cache-11.10.3.tgz";
        sha512 = "Psmp/7ovAa8appWh3g51goxu/z3iVms7JXOreq136D8Bbn6dYraPnmL6mdM8GThEx9vwSn92Fz+mGSjBzN8UPQ==";
      };
    };
    "@emotion/is-prop-valid-1.2.0" = {
      name = "_at_emotion_slash_is-prop-valid";
      packageName = "@emotion/is-prop-valid";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/is-prop-valid/-/is-prop-valid-1.2.0.tgz";
        sha512 = "3aDpDprjM0AwaxGE09bOPkNxHpBd+kA6jty3RnaEXdweX1DF1U3VQpPYb0g1IStAuK7SVQ1cy+bNBBKp4W3Fjg==";
      };
    };
    "@emotion/memoize-0.8.0" = {
      name = "_at_emotion_slash_memoize";
      packageName = "@emotion/memoize";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/memoize/-/memoize-0.8.0.tgz";
        sha512 = "G/YwXTkv7Den9mXDO7AhLWkE3q+I92B+VqAE+dYG4NGPaHZGvt3G8Q0p9vmE+sq7rTGphUbAvmQ9YpbfMQGGlA==";
      };
    };
    "@emotion/sheet-1.2.0" = {
      name = "_at_emotion_slash_sheet";
      packageName = "@emotion/sheet";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/sheet/-/sheet-1.2.0.tgz";
        sha512 = "OiTkRgpxescko+M51tZsMq7Puu/KP55wMT8BgpcXVG2hqXc0Vo0mfymJ/Uj24Hp0i083ji/o0aLddh08UEjq8w==";
      };
    };
    "@emotion/utils-1.2.0" = {
      name = "_at_emotion_slash_utils";
      packageName = "@emotion/utils";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/utils/-/utils-1.2.0.tgz";
        sha512 = "sn3WH53Kzpw8oQ5mgMmIzzyAaH2ZqFEbozVVBSYp538E06OSE6ytOp7pRAjNQR+Q/orwqdQYJSe2m3hCOeznkw==";
      };
    };
    "@emotion/weak-memoize-0.3.0" = {
      name = "_at_emotion_slash_weak-memoize";
      packageName = "@emotion/weak-memoize";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emotion/weak-memoize/-/weak-memoize-0.3.0.tgz";
        sha512 = "AHPmaAx+RYfZz0eYu6Gviiagpmiyw98ySSlQvCUhVGDRtDFe4DBS0x1bSjdF3gqUDYOczB+yYvBTtEylYSdRhg==";
      };
    };
    "@jridgewell/gen-mapping-0.1.1" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.1.1.tgz";
        sha512 = "sQXCasFk+U8lWYEe66WxRDOE9PjVz4vSM51fTu3Hw+ClTpUSQb718772vH3pyS5pShp6lvQM7SxgIDXXXmOX7w==";
      };
    };
    "@jridgewell/gen-mapping-0.3.2" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.2.tgz";
        sha512 = "mh65xKQAzI6iBcFzwv28KVWSmCkdRBWoOh+bYQGW3+6OZvbbN3TqMGo5hqYxQniRcH9F2VZIoJCm4pa3BPDK/A==";
      };
    };
    "@jridgewell/resolve-uri-3.1.0" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.0.tgz";
        sha512 = "F2msla3tad+Mfht5cJq7LSXcdudKTWCVYUgw6pLFOOHSTtZlj6SWNYAp+AhuqLmWdBO2X5hPrLcu8cVP8fy28w==";
      };
    };
    "@jridgewell/set-array-1.1.2" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.1.2.tgz";
        sha512 = "xnkseuNADM0gt2bs+BvhO0p78Mk762YnZdsuzFV018NoG1Sj1SCQvpSqa7XUaTam5vAGasABV9qXASMKnFMwMw==";
      };
    };
    "@jridgewell/sourcemap-codec-1.4.14" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.4.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.4.14.tgz";
        sha512 = "XPSJHWmi394fuUuzDnGz1wiKqWfo1yXecHQMRf2l6hztTO+nPru658AyDngaBe7isIxEkRsPR3FZh+s7iVa4Uw==";
      };
    };
    "@jridgewell/trace-mapping-0.3.15" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.15.tgz";
        sha512 = "oWZNOULl+UbhsgB51uuZzglikfIKSUBO/M9W2OfEjn7cmqoAiCgmv9lyACTUacZwBz0ITnJ2NqjU8Tx0DHL88g==";
      };
    };
    "@mui/base-5.0.0-alpha.98" = {
      name = "_at_mui_slash_base";
      packageName = "@mui/base";
      version = "5.0.0-alpha.98";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/base/-/base-5.0.0-alpha.98.tgz";
        sha512 = "c0U51+K2m57MASpRrmNs6qTXSvktDbVcSjD8zCRPbfuwYWERGGwNxwM3/jsBa4dSojTSmLPnOBFDypl74Ds6yQ==";
      };
    };
    "@mui/core-downloads-tracker-5.10.6" = {
      name = "_at_mui_slash_core-downloads-tracker";
      packageName = "@mui/core-downloads-tracker";
      version = "5.10.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/core-downloads-tracker/-/core-downloads-tracker-5.10.6.tgz";
        sha512 = "dmyQBqrKmVU6yCSM4GGal5qNXpViXX+/V1t0GA1A5i9QF5Gx6noV/cw0hrSS2ffLT8L2oScq1oTdA6NVIiQ8lg==";
      };
    };
    "@mui/material-5.10.6" = {
      name = "_at_mui_slash_material";
      packageName = "@mui/material";
      version = "5.10.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/material/-/material-5.10.6.tgz";
        sha512 = "QilW5PAAGSQdN7Cpp4rwSQ1doJAt3ca1a2PHZtr8RLVlpHnXb+qQ8CeDo9+9V2fK5CDNdtTN1F+iJKO43aFBpQ==";
      };
    };
    "@mui/private-theming-5.10.6" = {
      name = "_at_mui_slash_private-theming";
      packageName = "@mui/private-theming";
      version = "5.10.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/private-theming/-/private-theming-5.10.6.tgz";
        sha512 = "I/W0QyTLRdEx6py3lKAquKO/rNF/7j+nIOM/xCyI9kU0fcotVTcTY08mKMsS6vrzdWpi6pAkD0wP0KwWy5R5VA==";
      };
    };
    "@mui/styled-engine-5.10.6" = {
      name = "_at_mui_slash_styled-engine";
      packageName = "@mui/styled-engine";
      version = "5.10.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/styled-engine/-/styled-engine-5.10.6.tgz";
        sha512 = "OnVw5xnO4l0XzlJFhKif/RlLenBNhyEQQlSTwB9ApSWB05UAU5ZSbjNsRfyEKvgmQ/fPa+MqPD/dzxbIRCwyeg==";
      };
    };
    "@mui/system-5.10.6" = {
      name = "_at_mui_slash_system";
      packageName = "@mui/system";
      version = "5.10.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/system/-/system-5.10.6.tgz";
        sha512 = "HfQVX7e2xpQ3jtdB/WwtkFVtozMOozyN575/63u8ILHkE8wGDhblmCieAsnyJPFbm7WBW5PCMyzmfr4QyKLaYg==";
      };
    };
    "@mui/types-7.2.0" = {
      name = "_at_mui_slash_types";
      packageName = "@mui/types";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/types/-/types-7.2.0.tgz";
        sha512 = "lGXtFKe5lp3UxTBGqKI1l7G8sE2xBik8qCfrLHD5olwP/YU0/ReWoWT7Lp1//ri32dK39oPMrJN8TgbkCSbsNA==";
      };
    };
    "@mui/utils-5.10.6" = {
      name = "_at_mui_slash_utils";
      packageName = "@mui/utils";
      version = "5.10.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mui/utils/-/utils-5.10.6.tgz";
        sha512 = "g0Qs8xN/MW2M3fLL8197h5J2VB9U+49fLlnKKqC6zy/yus5cZwdT+Gwec+wUMxgwQoxMDn+J8oDWAn28kEOR/Q==";
      };
    };
    "@popperjs/core-2.11.6" = {
      name = "_at_popperjs_slash_core";
      packageName = "@popperjs/core";
      version = "2.11.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@popperjs/core/-/core-2.11.6.tgz";
        sha512 = "50/17A98tWUfQ176raKiOGXuYpLyyVMkxxG6oylzL3BPOlA6ADGdK7EYunSa4I064xerltq9TGXs8HmOk5E+vw==";
      };
    };
    "@rollup/plugin-babel-5.3.1" = {
      name = "_at_rollup_slash_plugin-babel";
      packageName = "@rollup/plugin-babel";
      version = "5.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-babel/-/plugin-babel-5.3.1.tgz";
        sha512 = "WFfdLWU/xVWKeRQnKmIAQULUI7Il0gZnBIH/ZFO069wYIfPu+8zrfp/KMW0atmELoRDq8FbiP3VCss9MhCut7Q==";
      };
    };
    "@rollup/plugin-commonjs-22.0.2" = {
      name = "_at_rollup_slash_plugin-commonjs";
      packageName = "@rollup/plugin-commonjs";
      version = "22.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-commonjs/-/plugin-commonjs-22.0.2.tgz";
        sha512 = "//NdP6iIwPbMTcazYsiBMbJW7gfmpHom33u1beiIoHDEM0Q9clvtQB1T0efvMqHeKsGohiHo97BCPCkBXdscwg==";
      };
    };
    "@rollup/plugin-image-2.1.1" = {
      name = "_at_rollup_slash_plugin-image";
      packageName = "@rollup/plugin-image";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-image/-/plugin-image-2.1.1.tgz";
        sha512 = "AgP4U85zuQJdUopLUCM+hTf45RepgXeTb8EJsleExVy99dIoYpt3ZlDYJdKmAc2KLkNntCDg6BPJvgJU3uGF+g==";
      };
    };
    "@rollup/plugin-multi-entry-4.1.0" = {
      name = "_at_rollup_slash_plugin-multi-entry";
      packageName = "@rollup/plugin-multi-entry";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-multi-entry/-/plugin-multi-entry-4.1.0.tgz";
        sha512 = "nellK5pr50W0JA2+bDJbG8F79GBP802J40YRoC0wyfpTAeAn5mJ4eaFiB/MN+YoX9hgb/6RJoZl9leDjZnUFKw==";
      };
    };
    "@rollup/plugin-node-resolve-14.1.0" = {
      name = "_at_rollup_slash_plugin-node-resolve";
      packageName = "@rollup/plugin-node-resolve";
      version = "14.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-node-resolve/-/plugin-node-resolve-14.1.0.tgz";
        sha512 = "5G2niJroNCz/1zqwXtk0t9+twOSDlG00k1Wfd7bkbbXmwg8H8dvgHdIWAun53Ps/rckfvOC7scDBjuGFg5OaWw==";
      };
    };
    "@rollup/plugin-typescript-8.5.0" = {
      name = "_at_rollup_slash_plugin-typescript";
      packageName = "@rollup/plugin-typescript";
      version = "8.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-typescript/-/plugin-typescript-8.5.0.tgz";
        sha512 = "wMv1/scv0m/rXx21wD2IsBbJFba8wGF3ErJIr6IKRfRj49S85Lszbxb4DCo8iILpluTjk2GAAu9CoZt4G3ppgQ==";
      };
    };
    "@rollup/plugin-virtual-2.1.0" = {
      name = "_at_rollup_slash_plugin-virtual";
      packageName = "@rollup/plugin-virtual";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/plugin-virtual/-/plugin-virtual-2.1.0.tgz";
        sha512 = "CPPAtlKT53HFqC8jFHb/V5WErpU8Hrq2TyCR0A7kPQMlF2wNUf0o1xuAc+Qxj8NCZM0Z3Yvl+FbUXfJjVWqDwA==";
      };
    };
    "@rollup/pluginutils-3.1.0" = {
      name = "_at_rollup_slash_pluginutils";
      packageName = "@rollup/pluginutils";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@rollup/pluginutils/-/pluginutils-3.1.0.tgz";
        sha512 = "GksZ6pr6TpIjHm8h9lSQ8pi8BE9VeubNT0OMJ3B5uZJ8pz73NPiqOtCog/x2/QzM1ENChPKxMDhiQuRHsqc+lg==";
      };
    };
    "@types/estree-0.0.39" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "0.0.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-0.0.39.tgz";
        sha512 = "EYNwp3bU+98cpU4lAWYYL7Zz+2gryWH1qbdDTidVd6hkiR6weksdbMadyXKXNPEkQFhXM+hVO9ZygomHXp+AIw==";
      };
    };
    "@types/node-18.7.18" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "18.7.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-18.7.18.tgz";
        sha512 = "m+6nTEOadJZuTPkKR/SYK3A2d7FZrgElol9UP1Kae90VVU4a6mxnPuLiIW1m4Cq4gZ/nWb9GrdVXJCoCazDAbg==";
      };
    };
    "@types/prop-types-15.7.5" = {
      name = "_at_types_slash_prop-types";
      packageName = "@types/prop-types";
      version = "15.7.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/prop-types/-/prop-types-15.7.5.tgz";
        sha512 = "JCB8C6SnDoQf0cNycqd/35A7MjcnK+ZTqE7judS6o7utxUCg6imJg3QK2qzHKszlTjcj2cn+NwMB2i96ubpj7w==";
      };
    };
    "@types/react-18.0.20" = {
      name = "_at_types_slash_react";
      packageName = "@types/react";
      version = "18.0.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react/-/react-18.0.20.tgz";
        sha512 = "MWul1teSPxujEHVwZl4a5HxQ9vVNsjTchVA+xRqv/VYGCuKGAU6UhfrTdF5aBefwD1BHUD8i/zq+O/vyCm/FrA==";
      };
    };
    "@types/react-is-17.0.3" = {
      name = "_at_types_slash_react-is";
      packageName = "@types/react-is";
      version = "17.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react-is/-/react-is-17.0.3.tgz";
        sha512 = "aBTIWg1emtu95bLTLx0cpkxwGW3ueZv71nE2YFBpL8k/z5czEW8yYpOo8Dp+UUAFAtKwNaOsh/ioSeQnWlZcfw==";
      };
    };
    "@types/react-transition-group-4.4.5" = {
      name = "_at_types_slash_react-transition-group";
      packageName = "@types/react-transition-group";
      version = "4.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/react-transition-group/-/react-transition-group-4.4.5.tgz";
        sha512 = "juKD/eiSM3/xZYzjuzH6ZwpP+/lejltmiS3QEzV/vmb/Q8+HfDmxu+Baga8UEMGBqV88Nbg4l2hY/K2DkyaLLA==";
      };
    };
    "@types/resolve-1.17.1" = {
      name = "_at_types_slash_resolve";
      packageName = "@types/resolve";
      version = "1.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/resolve/-/resolve-1.17.1.tgz";
        sha512 = "yy7HuzQhj0dhGpD8RLXSZWEkLsV9ibvxvi6EiJ3bkqLAO1RGo0WbkWQiwpRlSFymTJRz0d3k5LM3kkx8ArDbLw==";
      };
    };
    "@types/scheduler-0.16.2" = {
      name = "_at_types_slash_scheduler";
      packageName = "@types/scheduler";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/scheduler/-/scheduler-0.16.2.tgz";
        sha512 = "hppQEBDmlwhFAXKJX2KnWLYu5yMfi91yazPb2l+lbJiwW+wdo1gNeRA+3RgNSO39WYX2euey41KEwnqesU2Jew==";
      };
    };
    "ansi-styles-3.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "3.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-3.2.1.tgz";
        sha512 = "VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "browserslist-4.21.4" = {
      name = "browserslist";
      packageName = "browserslist";
      version = "4.21.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/browserslist/-/browserslist-4.21.4.tgz";
        sha512 = "CBHJJdDmgjl3daYjN5Cp5kbTf1mUhZoS+beLklHIvkOWscs83YAhLlF3Wsh/lciQYAcbBJgTOD44VtG31ZM4Hw==";
      };
    };
    "builtin-modules-3.3.0" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-3.3.0.tgz";
        sha512 = "zhaCDicdLuWN5UbN5IMnFqNMhNfo919sH85y2/ea+5Yg9TsTkeZxpL+JLbp6cgYFS4sRLp3YV4S6yDuqVWHYOw==";
      };
    };
    "caniuse-lite-1.0.30001409" = {
      name = "caniuse-lite";
      packageName = "caniuse-lite";
      version = "1.0.30001409";
      src = fetchurl {
        url = "https://registry.npmjs.org/caniuse-lite/-/caniuse-lite-1.0.30001409.tgz";
        sha512 = "V0mnJ5dwarmhYv8/MzhJ//aW68UpvnQBXv8lJ2QUsvn2pHcmAuNtu8hQEDz37XnA1iE+lRR9CIfGWWpgJ5QedQ==";
      };
    };
    "chalk-2.4.2" = {
      name = "chalk";
      packageName = "chalk";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-2.4.2.tgz";
        sha512 = "Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==";
      };
    };
    "clsx-1.2.1" = {
      name = "clsx";
      packageName = "clsx";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clsx/-/clsx-1.2.1.tgz";
        sha512 = "EcR6r5a8bj6pu3ycsa/E/cKVGuTgZJZdsyUYHOksG/UHIiKfjxzRxYJpyVBwYaQeOvghal9fcc4PidlgzugAQg==";
      };
    };
    "color-convert-1.9.3" = {
      name = "color-convert";
      packageName = "color-convert";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-convert/-/color-convert-1.9.3.tgz";
        sha512 = "QfAUtd+vFdAtFQcC8CCyYt1fYWxSqAiK2cSD6zDB8N3cpsEBAvRxp9zOGg6G/SHHJYAT88/az/IuDGALsNVbGg==";
      };
    };
    "color-name-1.1.3" = {
      name = "color-name";
      packageName = "color-name";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/color-name/-/color-name-1.1.3.tgz";
        sha512 = "72fSenhMw2HZMTVHeCA9KCmpEIbzWiQsjN+BHcBbS9vr1mtt+vJjPdksIBNUmKAW8TFUDPJK5SUU3QhE9NEXDw==";
      };
    };
    "commondir-1.0.1" = {
      name = "commondir";
      packageName = "commondir";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commondir/-/commondir-1.0.1.tgz";
        sha512 = "W9pAhw0ja1Edb5GVdIF1mjZw/ASI0AlShXM83UUGe2DVr5TdAPEA1OA8m/g8zWp9x6On7gqufY+FatDbC3MDQg==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha512 = "/Srv4dswyQNBfohGpz9o6Yb3Gz3SrUDqBH5rTuhGR7ahtlbYKnVxw2bCFMRljaA7EXHaXZ8wsHdodFvbkhKmqg==";
      };
    };
    "convert-source-map-1.8.0" = {
      name = "convert-source-map";
      packageName = "convert-source-map";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/convert-source-map/-/convert-source-map-1.8.0.tgz";
        sha512 = "+OQdjP49zViI/6i7nIJpA8rAl4sV/JdPfU9nZs3VqOwGIgizICvuN2ru6fMd+4llL0tar18UYJXfZ/TWtmhUjA==";
      };
    };
    "csstype-3.1.1" = {
      name = "csstype";
      packageName = "csstype";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/csstype/-/csstype-3.1.1.tgz";
        sha512 = "DJR/VvkAvSZW9bTouZue2sSxDwdTN92uHjqeKVm+0dAqdfNykRzQ95tay8aXMBAAPpUiq4Qcug2L7neoRh2Egw==";
      };
    };
    "debug-4.3.4" = {
      name = "debug";
      packageName = "debug";
      version = "4.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.3.4.tgz";
        sha512 = "PRWFHuSU3eDtQJPvnNY7Jcket1j0t5OuOsFzPPzsekD52Zl8qUfFIPEiswXqIvHWGVHOgX+7G/vCNNhehwxfkQ==";
      };
    };
    "deepmerge-4.2.2" = {
      name = "deepmerge";
      packageName = "deepmerge";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/deepmerge/-/deepmerge-4.2.2.tgz";
        sha512 = "FJ3UgI4gIl+PHZm53knsuSFpE+nESMr7M4v9QcgB7S63Kj/6WqMiFQJpBBYz1Pt+66bZpP3Q7Lye0Oo9MPKEdg==";
      };
    };
    "dom-helpers-5.2.1" = {
      name = "dom-helpers";
      packageName = "dom-helpers";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-helpers/-/dom-helpers-5.2.1.tgz";
        sha512 = "nRCa7CK3VTrM2NmGkIy4cbK7IZlgBE/PYMn55rrXefr5xXDP0LdtfPnblFDoVdcAfslJ7or6iqAUnx0CCGIWQA==";
      };
    };
    "electron-to-chromium-1.4.257" = {
      name = "electron-to-chromium";
      packageName = "electron-to-chromium";
      version = "1.4.257";
      src = fetchurl {
        url = "https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.4.257.tgz";
        sha512 = "C65sIwHqNnPC2ADMfse/jWTtmhZMII+x6ADI9gENzrOiI7BpxmfKFE84WkIEl5wEg+7+SfIkwChDlsd1Erju2A==";
      };
    };
    "escalade-3.1.1" = {
      name = "escalade";
      packageName = "escalade";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/escalade/-/escalade-3.1.1.tgz";
        sha512 = "k0er2gUkLf8O0zKJiAhmkTnJlTvINGv7ygDNPbeIsX/TJjGJZHuh9B2UxbsaEkmlEo9MfhrSzmhIlhRlI2GXnw==";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha512 = "vbRorB5FUQWvla16U8R/qgaFIya2qGzwDrNmCZuYKrbdSUMG6I1ZCGQRefkRVhuOkIGVne7BQ35DSfo1qvJqFg==";
      };
    };
    "estree-walker-1.0.1" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-1.0.1.tgz";
        sha512 = "1fMXF3YP4pZZVozF8j/ZLfvnR8NSIljt56UhbZ5PeeDmmGHpgpdwQt7ITlGvYaQukCvuBRMLEiKiYC+oeIg4cg==";
      };
    };
    "estree-walker-2.0.2" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-2.0.2.tgz";
        sha512 = "Rfkk/Mp/DL7JVje3u18FxFujQlTNR2q6QfMSMB7AvCBx91NGj/ba3kCfza0f6dVDbw7YlRf/nDrn7pQrCCyQ/w==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha512 = "OO0pH2lK6a0hZnAdau5ItzHPI6pUlvI7jMVnxUQRtw4owF2wk8lOSabtGDCTP4Ggrg2MbGnWO9X8K1t4+fGMDw==";
      };
    };
    "fsevents-2.3.2" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-2.3.2.tgz";
        sha512 = "xiqMQR4xAeHTuB9uWm+fFRcIOgKBMiOBP+eXiyT7jsgVCq1bkVygt00oASowB7EdtpOHaaPgKt812P9ab+DDKA==";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "gensync-1.0.0-beta.2" = {
      name = "gensync";
      packageName = "gensync";
      version = "1.0.0-beta.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/gensync/-/gensync-1.0.0-beta.2.tgz";
        sha512 = "3hN7NaskYvMDLQY55gnW3NQ+mesEAepTqlg+VEbj7zzqEMBVNhzcGYYeqFo/TlYz6eQiFcp1HcsCZO+nGgS8zg==";
      };
    };
    "glob-7.2.3" = {
      name = "glob";
      packageName = "glob";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.2.3.tgz";
        sha512 = "nFR0zLpU2YCaRxwoCJvL6UvCH2JFyFVIvwTLsIf21AuHlMskA1hhTdk+LlYJtOlYt9v6dvszD2BGRqBL+iQK9Q==";
      };
    };
    "globals-11.12.0" = {
      name = "globals";
      packageName = "globals";
      version = "11.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/globals/-/globals-11.12.0.tgz";
        sha512 = "WOBp/EEGUiIsJSp7wcv/y6MO+lV9UoncWqxuFfm8eBwzWNgyfBd6Gz+IeKQ9jCmyhoH99g15M3T+QaVHFjizVA==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-flag-3.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-3.0.0.tgz";
        sha512 = "sKJf1+ceQBr4SMkvQnBDNDtf4TXpVhVGateu0t918bl30FnbE2m4vNLX+VWe/dpjlb+HugGYzW7uQXH98HPEYw==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha512 = "k92I/b08q4wvFscXCLvqfsHCrjrF7yiXsQuIVvVE7N82W3+aqpzuUdBbfhWcy/FZR3/4IgflMgKLOsvPDrGCJA==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-builtin-module-3.2.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-3.2.0.tgz";
        sha512 = "phDA4oSGt7vl1n5tJvTWooWWAsXLY+2xCnxNqvKhGEzujg+A43wPlPOyDg3C8XQHN+6k/JTQWJ/j0dQh/qr+Hw==";
      };
    };
    "is-core-module-2.10.0" = {
      name = "is-core-module";
      packageName = "is-core-module";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-core-module/-/is-core-module-2.10.0.tgz";
        sha512 = "Erxj2n/LDAZ7H8WNJXd9tw38GYM3dv8rk8Zcs+jJuxYTW7sozH+SS8NtrSjVL1/vpLvWi1hxy96IzjJ3EHTJJg==";
      };
    };
    "is-module-1.0.0" = {
      name = "is-module";
      packageName = "is-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-module/-/is-module-1.0.0.tgz";
        sha512 = "51ypPSPCoTEIN9dy5Oy+h4pShgJmPCygKfyRCISBI+JoWT/2oJvK8QPxmwv7b/p239jXrm9M1mlQbyKJ5A152g==";
      };
    };
    "is-reference-1.2.1" = {
      name = "is-reference";
      packageName = "is-reference";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-reference/-/is-reference-1.2.1.tgz";
        sha512 = "U82MsXXiFIrjCK4otLT+o2NA2Cd2g5MLoOVXUZjIOhLurrRxpEXzI8O0KZHr3IjLvlAH1kTPYSuqer5T9ZVBKQ==";
      };
    };
    "js-tokens-4.0.0" = {
      name = "js-tokens";
      packageName = "js-tokens";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-tokens/-/js-tokens-4.0.0.tgz";
        sha512 = "RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==";
      };
    };
    "jsesc-2.5.2" = {
      name = "jsesc";
      packageName = "jsesc";
      version = "2.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsesc/-/jsesc-2.5.2.tgz";
        sha512 = "OYu7XEzjkCQ3C5Ps3QIZsQfNpqoJyZZA99wd9aWd05NCtC5pWOkShK2mkL6HXQR6/Cy2lbNdPlZBpuQHXE63gA==";
      };
    };
    "json5-2.2.1" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.1.tgz";
        sha512 = "1hqLFMSrGHRHxav9q9gNjJ5EXznIxGVO09xQRrwplcS8qs28pZ8s8hupZAmqDwZUmVZ2Qb2jnyPOWcDH8m8dlA==";
      };
    };
    "loose-envify-1.4.0" = {
      name = "loose-envify";
      packageName = "loose-envify";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/loose-envify/-/loose-envify-1.4.0.tgz";
        sha512 = "lyuxPGr/Wfhrlem2CL/UcnUc1zcqKAImBDzukY7Y5F/yQiNdko6+fRLevlw1HgMySw7f611UIY408EtxRSoK3Q==";
      };
    };
    "magic-string-0.25.9" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.25.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.25.9.tgz";
        sha512 = "RmF0AsMzgt25qzqqLc1+MbHmhdx0ojF2Fvs4XnOqz2ZOBXzzkEwc/dJQZCYHAn7v1jbVOjAZfK8msRn4BxO4VQ==";
      };
    };
    "magic-string-0.26.4" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.26.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.26.4.tgz";
        sha512 = "e5uXtVJ22aEpK9u1+eQf0fSxHeqwyV19K+uGnlROCxUhzwRip9tBsaMViK/0vC3viyPd5Gtucp3UmEp/Q2cPTQ==";
      };
    };
    "matched-5.0.1" = {
      name = "matched";
      packageName = "matched";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/matched/-/matched-5.0.1.tgz";
        sha512 = "E1fhSTPRyhAlNaNvGXAgZQlq1hL0bgYMTk/6bktVlIhzUnX/SZs7296ACdVeNJE8xFNGSuvd9IpI7vSnmcqLvw==";
      };
    };
    "mini-svg-data-uri-1.4.4" = {
      name = "mini-svg-data-uri";
      packageName = "mini-svg-data-uri";
      version = "1.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mini-svg-data-uri/-/mini-svg-data-uri-1.4.4.tgz";
        sha512 = "r9deDe9p5FJUPZAk3A59wGH7Ii9YrjjWw0jmw/liSbHl2CHiyXj6FcDXDu2K3TjVAXqiJdaw3xxwlZZr9E6nHg==";
      };
    };
    "minimatch-3.1.2" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.1.2.tgz";
        sha512 = "J7p63hRiAjw1NDEww1W7i37+ByIrOWO5XQQAzZ3VOcL0PNybwpfmV/N05zFAzwQ9USyEcX6t3UO+K5aqBQOIHw==";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "node-releases-2.0.6" = {
      name = "node-releases";
      packageName = "node-releases";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-releases/-/node-releases-2.0.6.tgz";
        sha512 = "PiVXnNuFm5+iYkLBNeq5211hvO38y63T0i2KKh2KnUs3RpzJ+JtODFjkD8yjLwnDkTYF1eKXheUwdssR+NRZdg==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "path-parse-1.0.7" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.7.tgz";
        sha512 = "LDJzPVEEEPR+y48z93A0Ed0yXb8pAByGWo/k5YYdYgpY2/2EsOsksJrq7lOHxryrVOn1ejG6oAp8ahvOIQD8sw==";
      };
    };
    "picocolors-1.0.0" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.0.0.tgz";
        sha512 = "1fygroTLlHu66zi26VoTDv8yRgm0Fccecssto+MhsZ0D/DGW2sm8E8AjW7NU5VVTRt5GxbeZ5qBuJr+HyLYkjQ==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "prop-types-15.8.1" = {
      name = "prop-types";
      packageName = "prop-types";
      version = "15.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prop-types/-/prop-types-15.8.1.tgz";
        sha512 = "oj87CgZICdulUohogVAR7AjlC0327U4el4L6eAvOqCeudMDVU0NThNaV+b9Df4dXgSP1gXMTnPdhfe/2qDH5cg==";
      };
    };
    "react-18.2.0" = {
      name = "react";
      packageName = "react";
      version = "18.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react/-/react-18.2.0.tgz";
        sha512 = "/3IjMdb2L9QbBdWiW5e3P2/npwMBaU9mHCSCUzNln0ZCYbcfTsGbTJrU/kGemdH2IWmB2ioZ+zkxtmq6g09fGQ==";
      };
    };
    "react-dom-18.2.0" = {
      name = "react-dom";
      packageName = "react-dom";
      version = "18.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-dom/-/react-dom-18.2.0.tgz";
        sha512 = "6IMTriUmvsjHUjNtEDudZfuDQUoWXVxKHhlEGSk81n4YFS+r/Kl99wXiwlVXtPBtJenozv2P+hxDsw9eA7Xo6g==";
      };
    };
    "react-is-16.13.1" = {
      name = "react-is";
      packageName = "react-is";
      version = "16.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-16.13.1.tgz";
        sha512 = "24e6ynE2H+OKt4kqsOvNd8kBpV65zoxbA4BVsEOB3ARVWQki/DHzaUoC5KuON/BiccDaCCTZBuOcfZs70kR8bQ==";
      };
    };
    "react-is-18.2.0" = {
      name = "react-is";
      packageName = "react-is";
      version = "18.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-is/-/react-is-18.2.0.tgz";
        sha512 = "xWGDIW6x921xtzPkhiULtthJHoJvBbF3q26fzloPCK0hsvxtPVelvftw3zjbHWSkR2km9Z+4uxbDDK/6Zw9B8w==";
      };
    };
    "react-transition-group-4.4.5" = {
      name = "react-transition-group";
      packageName = "react-transition-group";
      version = "4.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/react-transition-group/-/react-transition-group-4.4.5.tgz";
        sha512 = "pZcd1MCJoiKiBR2NRxeCRg13uCXbydPnmB4EOeRrY7480qNWO8IIgQG6zlDkm6uRMsURXPuKq0GWtiM59a5Q6g==";
      };
    };
    "regenerator-runtime-0.13.9" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.9.tgz";
        sha512 = "p3VT+cOEgxFsRRA9X4lkI1E+k2/CtnKtU4gcxyaCUreilL/vqI6CdZ3wxVUx3UOUg+gnUOQQcRI7BmSI656MYA==";
      };
    };
    "resolve-1.22.1" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.22.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.22.1.tgz";
        sha512 = "nBpuuYuY5jFsli/JIs1oldw6fOQCBioohqWZg/2hiaOybXOft4lonv85uDOKXdf8rhyK159cxU5cDcK/NKk8zw==";
      };
    };
    "rollup-2.79.1" = {
      name = "rollup";
      packageName = "rollup";
      version = "2.79.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup/-/rollup-2.79.1.tgz";
        sha512 = "uKxbd0IhMZOhjAiD5oAFp7BqvkA4Dv47qpOCtaNvng4HBwdbWtdOh8f5nZNuk2rp51PMGk3bzfWu5oayNEuYnw==";
      };
    };
    "rollup-plugin-dts-4.2.2" = {
      name = "rollup-plugin-dts";
      packageName = "rollup-plugin-dts";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rollup-plugin-dts/-/rollup-plugin-dts-4.2.2.tgz";
        sha512 = "A3g6Rogyko/PXeKoUlkjxkP++8UDVpgA7C+Tdl77Xj4fgEaIjPSnxRmR53EzvoYy97VMVwLAOcWJudaVAuxneQ==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "scheduler-0.23.0" = {
      name = "scheduler";
      packageName = "scheduler";
      version = "0.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/scheduler/-/scheduler-0.23.0.tgz";
        sha512 = "CtuThmgHNg7zIZWAXi3AsyIzA3n4xx7aNyjwC2VJldO2LMVDhFK+63xGqq6CsJH4rTAt6/M+N4GhZiDYPx9eUw==";
      };
    };
    "semver-6.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "6.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-6.3.0.tgz";
        sha512 = "b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw==";
      };
    };
    "sourcemap-codec-1.4.8" = {
      name = "sourcemap-codec";
      packageName = "sourcemap-codec";
      version = "1.4.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/sourcemap-codec/-/sourcemap-codec-1.4.8.tgz";
        sha512 = "9NykojV5Uih4lgo5So5dtw+f0JgJX30KCNI8gwhz2J9A15wD0Ml6tjHKwf6fTSa6fAdVBdZeNOs9eJ71qCk8vA==";
      };
    };
    "stylis-4.0.13" = {
      name = "stylis";
      packageName = "stylis";
      version = "4.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/stylis/-/stylis-4.0.13.tgz";
        sha512 = "xGPXiFVl4YED9Jh7Euv2V220mriG9u4B2TA6Ybjc1catrstKD2PpIdU3U0RKpkVBC2EhmL/F0sPCr9vrFTNRag==";
      };
    };
    "supports-color-5.5.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-5.5.0.tgz";
        sha512 = "QjVjwdXIt408MIiAqCX4oUKsgU2EqAGzs2Ppkm4aQYbjm+ZEWEcW4SfFNTr4uMNZma0ey4f5lgLrkB0aX0QMow==";
      };
    };
    "supports-preserve-symlinks-flag-1.0.0" = {
      name = "supports-preserve-symlinks-flag";
      packageName = "supports-preserve-symlinks-flag";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-preserve-symlinks-flag/-/supports-preserve-symlinks-flag-1.0.0.tgz";
        sha512 = "ot0WnXS9fgdkgIcePe6RHNk1WA8+muPa6cSjeR3V8K27q9BB1rTE3R1p7Hv0z1ZyAc8s6Vvv8DIyWf681MAt0w==";
      };
    };
    "to-fast-properties-2.0.0" = {
      name = "to-fast-properties";
      packageName = "to-fast-properties";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-fast-properties/-/to-fast-properties-2.0.0.tgz";
        sha512 = "/OaKK0xYrs3DmxRYqL/yDc+FxFUVYhDlXMhRmv3z915w2HF1tnN1omB354j8VUGO/hbRzyD6Y3sA7v7GS/ceog==";
      };
    };
    "tslib-2.4.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.4.0.tgz";
        sha512 = "d6xOpEDfsi2CZVlPQzGeux8XMwLT9hssAsaPYExaQMuYskwb+x1x7J371tWlbBdWHroy99KnVB6qIkUbs5X3UQ==";
      };
    };
    "typescript-4.8.3" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.8.3.tgz";
        sha512 = "goMHfm00nWPa8UvR/CPSvykqf6dVV8x/dp0c5mFTMTIu0u0FlGWRioyy7Nn0PGAdHxpJZnuO/ut+PpQ8UiHAig==";
      };
    };
    "update-browserslist-db-1.0.9" = {
      name = "update-browserslist-db";
      packageName = "update-browserslist-db";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/update-browserslist-db/-/update-browserslist-db-1.0.9.tgz";
        sha512 = "/xsqn21EGVdXI3EXSum1Yckj3ZVZugqyOZQ/CxYPBD/R+ko9NSUScf8tFF4dOKY+2pvSSJA/S+5B8s4Zr4kyvg==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
  };
  args = {
    name = "secunet-mui-theme";
    packageName = "secunet-mui-theme";
    version = "1.0.0";
    src = ./..;
    dependencies = [
      sources."@ampproject/remapping-2.2.0"
      sources."@babel/code-frame-7.18.6"
      sources."@babel/compat-data-7.19.1"
      sources."@babel/core-7.19.1"
      (sources."@babel/generator-7.19.0" // {
        dependencies = [
          sources."@jridgewell/gen-mapping-0.3.2"
        ];
      })
      sources."@babel/helper-compilation-targets-7.19.1"
      sources."@babel/helper-environment-visitor-7.18.9"
      sources."@babel/helper-function-name-7.19.0"
      sources."@babel/helper-hoist-variables-7.18.6"
      sources."@babel/helper-module-imports-7.18.6"
      sources."@babel/helper-module-transforms-7.19.0"
      sources."@babel/helper-simple-access-7.18.6"
      sources."@babel/helper-split-export-declaration-7.18.6"
      sources."@babel/helper-string-parser-7.18.10"
      sources."@babel/helper-validator-identifier-7.19.1"
      sources."@babel/helper-validator-option-7.18.6"
      sources."@babel/helpers-7.19.0"
      sources."@babel/highlight-7.18.6"
      sources."@babel/parser-7.19.1"
      sources."@babel/runtime-7.19.0"
      sources."@babel/template-7.18.10"
      sources."@babel/traverse-7.19.1"
      sources."@babel/types-7.19.0"
      sources."@emotion/cache-11.10.3"
      sources."@emotion/is-prop-valid-1.2.0"
      sources."@emotion/memoize-0.8.0"
      sources."@emotion/sheet-1.2.0"
      sources."@emotion/utils-1.2.0"
      sources."@emotion/weak-memoize-0.3.0"
      sources."@jridgewell/gen-mapping-0.1.1"
      sources."@jridgewell/resolve-uri-3.1.0"
      sources."@jridgewell/set-array-1.1.2"
      sources."@jridgewell/sourcemap-codec-1.4.14"
      sources."@jridgewell/trace-mapping-0.3.15"
      sources."@mui/base-5.0.0-alpha.98"
      sources."@mui/core-downloads-tracker-5.10.6"
      sources."@mui/material-5.10.6"
      sources."@mui/private-theming-5.10.6"
      sources."@mui/styled-engine-5.10.6"
      sources."@mui/system-5.10.6"
      sources."@mui/types-7.2.0"
      sources."@mui/utils-5.10.6"
      sources."@popperjs/core-2.11.6"
      sources."@rollup/plugin-babel-5.3.1"
      sources."@rollup/plugin-commonjs-22.0.2"
      sources."@rollup/plugin-image-2.1.1"
      sources."@rollup/plugin-multi-entry-4.1.0"
      sources."@rollup/plugin-node-resolve-14.1.0"
      sources."@rollup/plugin-typescript-8.5.0"
      sources."@rollup/plugin-virtual-2.1.0"
      (sources."@rollup/pluginutils-3.1.0" // {
        dependencies = [
          sources."estree-walker-1.0.1"
        ];
      })
      sources."@types/estree-0.0.39"
      sources."@types/node-18.7.18"
      sources."@types/prop-types-15.7.5"
      sources."@types/react-18.0.20"
      sources."@types/react-is-17.0.3"
      sources."@types/react-transition-group-4.4.5"
      sources."@types/resolve-1.17.1"
      sources."@types/scheduler-0.16.2"
      sources."ansi-styles-3.2.1"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."browserslist-4.21.4"
      sources."builtin-modules-3.3.0"
      sources."caniuse-lite-1.0.30001409"
      sources."chalk-2.4.2"
      sources."clsx-1.2.1"
      sources."color-convert-1.9.3"
      sources."color-name-1.1.3"
      sources."commondir-1.0.1"
      sources."concat-map-0.0.1"
      sources."convert-source-map-1.8.0"
      sources."csstype-3.1.1"
      sources."debug-4.3.4"
      sources."deepmerge-4.2.2"
      sources."dom-helpers-5.2.1"
      sources."electron-to-chromium-1.4.257"
      sources."escalade-3.1.1"
      sources."escape-string-regexp-1.0.5"
      sources."estree-walker-2.0.2"
      sources."fs.realpath-1.0.0"
      sources."fsevents-2.3.2"
      sources."function-bind-1.1.1"
      sources."gensync-1.0.0-beta.2"
      sources."glob-7.2.3"
      sources."globals-11.12.0"
      sources."has-1.0.3"
      sources."has-flag-3.0.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-builtin-module-3.2.0"
      sources."is-core-module-2.10.0"
      sources."is-module-1.0.0"
      sources."is-reference-1.2.1"
      sources."js-tokens-4.0.0"
      sources."jsesc-2.5.2"
      sources."json5-2.2.1"
      sources."loose-envify-1.4.0"
      sources."magic-string-0.25.9"
      sources."matched-5.0.1"
      sources."mini-svg-data-uri-1.4.4"
      sources."minimatch-3.1.2"
      sources."ms-2.1.2"
      sources."node-releases-2.0.6"
      sources."object-assign-4.1.1"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.7"
      sources."picocolors-1.0.0"
      sources."picomatch-2.3.1"
      (sources."prop-types-15.8.1" // {
        dependencies = [
          sources."react-is-16.13.1"
        ];
      })
      sources."react-18.2.0"
      sources."react-dom-18.2.0"
      sources."react-is-18.2.0"
      sources."react-transition-group-4.4.5"
      sources."regenerator-runtime-0.13.9"
      sources."resolve-1.22.1"
      sources."rollup-2.79.1"
      (sources."rollup-plugin-dts-4.2.2" // {
        dependencies = [
          sources."magic-string-0.26.4"
        ];
      })
      sources."safe-buffer-5.1.2"
      sources."scheduler-0.23.0"
      sources."semver-6.3.0"
      sources."sourcemap-codec-1.4.8"
      sources."stylis-4.0.13"
      sources."supports-color-5.5.0"
      sources."supports-preserve-symlinks-flag-1.0.0"
      sources."to-fast-properties-2.0.0"
      sources."tslib-2.4.0"
      sources."typescript-4.8.3"
      sources."update-browserslist-db-1.0.9"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "";
      license = "ISC";
    };
    production = false;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
